
version: 0.1.{build}

image:
  - Visual Studio 2019

environment:
  matrix:
    # x86
    - CMAKE_GENERATOR_PLATFORM: x86
    
    # x64
    - CMAKE_GENERATOR_PLATFORM: x64


before_build:
 - cmd: cmake -H. -B./build

build:
  verbosity: normal
