
version: 0.1.{build}

image:
  - Visual Studio 2019

environment:
  configuration: Release
  CMAKE_GENERATOR: "Visual Studio 16 2019"
  matrix:
    # x86
    - platform: x86
      CMAKE_GENERATOR_PLATFORM: Win32
    
    # x64
    - platform: x64
      CMAKE_GENERATOR_PLATFORM: x64

before_build:
 - cmd: cmake -H. -B./build

build:
  verbosity: normal
