
version: 0.1.{build}

image:
  - Visual Studio 2019

configuration:
  - Release

platform:
  - x86
  - x64

before_build:
 - cmd: cmake -H. -B./build -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% -DCMAKE_BUILD_TYPE=%CONFIGURATION%

build:
  verbosity: normal
