
version: 1.0.{build}

image:
- Visual Studio 2019
# - Visual Studio 2017

configuration:
# - Debug
- Release

before_build:
- cmd: cmake -H. -B./build -DBUILD_SHARED_LIBS=%DBUILD_SHARED_LIBS%

build:
  verbosity: normal
